<?php

namespace app\modules\city\controllers;

use phpDocumentor\Reflection\Types\String_;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\captcha\CaptchaAction;

/**
 * Default controller for the `city` module
 */
class DefaultController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        //return parent::actions(); // TODO: Change the autogenerated stub
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() : string
    {
        return $this->render('index');
    }
}
