<?php

namespace app\modules\city\controllers;

use app\modules\city\models\City;
use phpDocumentor\Reflection\Types\String_;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\captcha\CaptchaAction;
use yii\web\NotFoundHttpException;

/**
 * Default controller for the `city` module
 */
class DefaultController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        //return parent::actions(); // TODO: Change the autogenerated stub
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex() : string
    {
        $cities = City::getAllWithFeedback();
        return $this->render('index', [
            'cities' => $cities
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView(int $id) : string
    {
        if (!$city = City::findOne(['id' => $id])) {
            throw new NotFoundHttpException("City with ID: $id does not exist.");
        }

        return $this->render('view', [
            'city' => $city
        ]);
    }
}
